export const defaultSettings: SettingsState = {
  backgroundRichness: "rich",
  syncSettings: true,
  navigationBar: "flexible",
  floatingCodeSpeed: 1800,
  disableCenterPainting: false,
  disableComments: false,
  disableGestures: false,
  disableSerifFont: false,
  disableEntryPopUp: false,
  disableBackgroundBlur: false,
  enableGallery: false,
  enableHalloweenEffect: false,
  disableSoundEffect: false,
  preferInitialGridView: false,
  pageTheme: {
    photos: "photos",
    home: "home",
    about: "about",
    management: "home",
    projects: "projects",
    blog: "blog",
  },
};
