export const defaultSettings: SettingsState = {
  backgroundRichness: "rich",
  syncSettings: true,
  navigationBar: "flexible",
  floatingCodeSpeed: 1800,
  disableCenterPainting: false,
  disableComments: false,
  disableGestures: false,
  disableSerifFont: false,
  disableEntryPopUp: false,
  enableGallery: false,
  enableHalloweenEffect: false,
  disableSoundEffect: false,
  preferInitialGridView: false,
  pageTheme: {
    home: "home",
    photos: "photos",
    blog: "blog",
    projects: "projects",
    about: "about",
    management: "bubbles",
  },
  disableToast: false,
  instantSearchResult: false,
  flyingBalloonRate: 1600,
  disableTableOfContents: false,
};
