import * as allThemes from "@/components/themes";

export const themeKeyMap: Record<ThemeAvailable, ThemeInterface> = {
  photos: allThemes.photosTheme,
  projects: allThemes.projectsTheme,
  home: allThemes.homeTheme,
  about: allThemes.aboutTheme,
  blog: allThemes.blogTheme,
  midnight: allThemes.midnightTheme,
  glitter: allThemes.glitterTheme,
  birthday: allThemes.birthdayTheme,
  plainLight: allThemes.plainLightTheme,
  plainDark: allThemes.plainDarkTheme,
  rainbow: allThemes.rainbowTheme,
  bubbles: allThemes.bubblesTheme,
  stars: allThemes.starsTheme,
  christmas: allThemes.christmasTheme,
  grass: allThemes.grassTheme,
  halloween: allThemes.halloweenTheme,
  gold: allThemes.goldTheme,
  autumnal: allThemes.autumnalTheme,
  cherry: allThemes.cherryTheme,
  marina: allThemes.marinaTheme,
  mori: allThemes.moriTheme,
  sky: allThemes.skyTheme,
  storm: allThemes.stormTheme,
  vitreous: allThemes.vitreousTheme,
  pixelland: allThemes.pixellandTheme,
};
