const gallery3DConfig: ThemeDataConfig = {
  palette: {
    primary: [49, 50, 54],
    saturated: [103, 93, 105],
    pastel: [176, 165, 158],
    light: [240, 239, 247],
    page: [
      {
        type: "radial-gradient",
        stops: [
          { color: [242, 182, 244], at: 0, opacity: 0.08 },
          { color: [255, 255, 255], at: 44, opacity: 0 },
        ],
        posX: 19.3,
        posY: 100.6,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          { color: [213, 169, 245], at: 0, opacity: 0.05 },
          { color: [255, 255, 255], at: 39.8, opacity: 0 },
        ],
        posX: 22.3,
        posY: 8.6,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          { color: [247, 225, 209], at: 0, opacity: 0.12 },
          { color: [255, 255, 255], at: 41.5, opacity: 0 },
        ],
        posX: 53.5,
        posY: 53.6,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          { color: [195, 243, 166], at: 0, opacity: 0.07 },
          { color: [255, 255, 255], at: 29.6, opacity: 0 },
        ],
        posX: 100.1,
        posY: 16.9,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          { color: [169, 199, 242], at: 0, opacity: 0.03 },
          { color: [255, 255, 255], at: 38, opacity: 0 },
        ],
        posX: 77.1,
        posY: 82.6,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          { color: [246, 169, 208], at: 0, opacity: 0.07 },
          { color: [255, 255, 255], at: 47.8, opacity: 0 },
        ],
        posX: 22.3,
        posY: 8.6,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          { color: [198, 245, 165], at: 0, opacity: 0.1 },
          { color: [255, 255, 255], at: 46.5, opacity: 0 },
        ],
        posX: 13.3,
        posY: 97.3,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          { color: [249, 186, 220], at: 0, opacity: 0.11 },
          { color: [255, 255, 255], at: 40.1, opacity: 0 },
        ],
        posX: 11.3,
        posY: 45.1,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          { color: [168, 247, 182], at: 0, opacity: 0.09 },
          { color: [255, 255, 255], at: 43.4, opacity: 0 },
        ],
        posX: 41.4,
        posY: 62.6,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          { color: [222, 240, 170], at: 0, opacity: 0.11 },
          { color: [255, 255, 255], at: 41.2, opacity: 0 },
        ],
        posX: 70.1,
        posY: 10.1,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          { color: [245, 181, 199], at: 0, opacity: 0.04 },
          { color: [255, 255, 255], at: 30.5, opacity: 0 },
        ],
        posX: 103.2,
        posY: 76.2,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "linear-gradient",
        stops: [
          { color: [254, 254, 254], opacity: 1, at: 0 },
          { color: [242, 242, 242], opacity: 1, at: 100 },
        ],
        angle: 180,
      },
    ],
    widget: [
      {
        type: "radial-gradient",
        stops: [
          {
            color: [247, 225, 209],
            at: 0,
            opacity: 0.24,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 32.5, opacity: 0 },
        ],
        posX: 53.5,
        posY: 53.6,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [247, 197, 236],
            at: 0,
            opacity: 0.09,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 37.3, opacity: 0 },
        ],
        posX: 50.7,
        posY: 98.5,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [246, 169, 208],
            at: 0,
            opacity: 0.15,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 39.8, opacity: 0 },
        ],
        posX: 22.3,
        posY: 8.6,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [243, 197, 246],
            at: 0,
            opacity: 0.06,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 24.1, opacity: 0 },
        ],
        posX: 54.8,
        posY: 77,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [195, 243, 166],
            at: 0,
            opacity: 0.15,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 21.6, opacity: 0 },
        ],
        posX: 100.1,
        posY: 16.9,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [163, 238, 246],
            at: 0,
            opacity: 0.21,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 31.4, opacity: 0 },
        ],
        posX: 47.5,
        posY: 82.9,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [169, 199, 242],
            at: 0,
            opacity: 0.07,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 27, opacity: 0 },
        ],
        posX: 77.1,
        posY: 82.6,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [178, 245, 241],
            at: 0,
            opacity: 0.21,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 21.8, opacity: 0 },
        ],
        posX: 75.7,
        posY: 53.6,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [198, 245, 165],
            at: 0,
            opacity: 0.2,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 39.5, opacity: 0 },
        ],
        posX: 13.3,
        posY: 97.3,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [249, 182, 176],
            at: 0,
            opacity: 0.23,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 27.7, opacity: 0 },
        ],
        posX: 73.1,
        posY: 47.7,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [242, 182, 244],
            at: 0,
            opacity: 0.17,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 35, opacity: 0 },
        ],
        posX: 19.3,
        posY: 100.6,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [200, 247, 239],
            at: 0,
            opacity: 0.21,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 20.1, opacity: 0 },
        ],
        posX: 18,
        posY: 36.7,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [249, 186, 220],
            at: 0,
            opacity: 0.23,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 31.1, opacity: 0 },
        ],
        posX: 11.3,
        posY: 45.1,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [250, 199, 193],
            at: 0,
            opacity: 0.1,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 21.9, opacity: 0 },
        ],
        posX: 8.6,
        posY: 16.2,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [168, 247, 182],
            at: 0,
            opacity: 0.18,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 36.4, opacity: 0 },
        ],
        posX: 41.4,
        posY: 62.6,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [248, 184, 207],
            at: 0,
            opacity: 0.1,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 36, opacity: 0 },
        ],
        posX: 91.2,
        posY: 68.9,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [222, 240, 170],
            at: 0,
            opacity: 0.22,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 32.2, opacity: 0 },
        ],
        posX: 70.1,
        posY: 10.1,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [230, 250, 206],
            at: 0,
            opacity: 0.24,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 31.2, opacity: 0 },
        ],
        posX: 83.9,
        posY: 27.2,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [245, 181, 199],
            at: 0,
            opacity: 0.09,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 23.5, opacity: 0 },
        ],
        posX: 103.2,
        posY: 76.2,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "radial-gradient",
        stops: [
          {
            color: [178, 242, 191],
            at: 0,
            opacity: 0.23,
            isWidgetOpacity: true,
          },
          { color: [255, 255, 255], at: 35.3, opacity: 0 },
        ],
        posX: 84,
        posY: 58.5,
        isCircle: true,
        sizeKeyword: "farthest-corner",
      },
      {
        type: "linear-gradient",
        stops: [
          { color: [246, 246, 246], opacity: 1, isWidgetOpacity: true, at: 20 },
          { color: [254, 254, 254], opacity: 1, isWidgetOpacity: true, at: 80 },
        ],
        angle: 45,
      },
    ],
  },
  siteThemeColor: "#fefefe",
  favicon: { mode: "custom", customKey: "gallery3D" },
  animatedBackgroundKey: "gallery3D",
};

export default gallery3DConfig;
